<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LOCKnet.Core\LOCKnet.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
      <Folder Include="Repositories\" />
    </ItemGroup>

</Project>
